version: "3.9"  # optional since v1.27.0
services:
  nginx:
    image: nginx-with-health-check-geoip2-vts:latest
    ports:
      - "80:80"
      - "11050:11050"
    restart: on-failure
    volumes:
      - ./log/:/var/log/nginx/
